apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/local/cluster-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
