apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: wordpress
spec:
  interval: 1h
  chart:
    spec:
      chart: mysql
      version: "9.14.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      rootPassword: "rootpassword"
      password: "wordpresspassword"
      username: wordpress
      database: wordpress
    primary:
      persistence:
        enabled: true
        size: 8Gi
