apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-password: wordpresspassword
  mysql-user: wordpress
  mysql-database: wordpress
