apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1h
  chart:
    spec:
      chart: wordpress
      version: "19.2.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressUsername: admin
    wordpressPassword: adminpassword
    wordpressEmail: admin@example.com
    wordpressFirstName: Admin
    wordpressLastName: User
    wordpressBlogName: "My WordPress Site"
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql
      user: wordpress
      password:
        secretKeyRef:
          name: mysql-secret
          key: mysql-password
      database: wordpress
      port: 3306
    service:
      type: ClusterIP
